experiment_name: 
seed: 3
model_name: AGMM
model_dataset: AGMM

model_arguments:
  d: 128
  num_encoder_layers: 2
  num_encoder_heads: 2
  num_item_attn_layers: 1
  num_item_attn_heads: 2
  num_gen_layers: 1
  num_gen_heads: 2
  k: 2
  hidden_dropout_prob: 0.3
  attn_dropout_prob: 0.3
  modal_dropout_prob: 0.5
  item_dropout_prob: 0.5
  use_positional_embedding: True
  max_len: 50

lr: 0.001
alpha: 0.7
beta: 0.5
scheduler: LambdaLR
scheduler_rate: 0.98
lr_step: 1
optimizer: adam

epoch: 1000
batch_size: 256
shuffle: true

weight_decay: 0.0005
num_workers: 8
valid_step: 1
data_name: HM
n_cuda: '0'
use_wandb: False
