# Base settings for common experiment
experiment_name: 
seed: 2001
model_name: "AGMM"

# dataset settings
model_dataset: "AGMM"

# model params settings
model_arguments:
  d: 64
  num_encoder_layers: 2  
  num_encoder_heads: 2    
  num_item_attn_layers : 1
  num_item_attn_heads : 2
  num_gen_layers: 1
  num_gen_heads: 2
  k: 2
  hidden_dropout_prob: 0.5   
  attn_dropout_prob: 0.5      
  modal_dropout_prob: 0.5
  item_dropout_prob: 0.5
  use_positional_embedding: True     
  max_len: 50   

# loss settings
lr: 0.001

alpha : 0.5
beta: 0.3
scheduler : "LambdaLR"
scheduler_rate : 0.98
lr_step : 1
optimizer : "adam"

# else
epoch: 1000
batch_size: 256
shuffle: True       # shuffle dataloader
weight_decay: 0.001 # weight decay for Adam
num_workers: 8
valid_step: 1 # number of steps to run validation
data_name: "Home"
n_cuda: "0"
use_wandb: False